### ISSUE TITLE
Publish library to MavenCentral

### ISSUE THREAD

**Issue by dautovicharis** [dautovicharis/Charts#97]

**Comment by pacjo** [comment]
Hey, I found your library and wanted to use it for my project, but it looks like you have different versions on maven and github:

maven: [1.3.1](https://mvnrepository.com/artifact/io.github.dautovicharis/charts/1.3.1)
github: [1.2.0](https://github.com/dautovicharis/Charts/releases/tag/1.2.0)

Are there any important differences between those?

**Comment by dautovicharis** [comment]
Hey @pacjo, 

`1.2.0` was an old release on Jitpack - it doesn't support multiplatform.
`1.3.1` was just a kind of test release to mavencentral.

I am currently preparing the 2.0.0 release, and I think it would be best that you use `2.0.0-SNAPSHOT`.

Please check the readme on how to use snapshot releases. If you have any questions let me know.

**Comment by pacjo** [comment]
> Please check the readme on how to use snapshot releases. If you have any questions let me know.

Thanks for the explanation. I got `2.0.0-SNAPSHOT` working without any issues.

Well, some issues, but they were also present in 1.3.1. When I update `items` in `BarChartView` with number of entries larger then before (e.g. from 7 to 24) I get `IndexOutOfBoundsException`
